version: '3.8'

services:
  pioneertown:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pioneertown.rule=Host(`localhost`)"
      - "traefik.http.services.pioneertown.loadbalancer.server.port=8080"

  # Optional: Add a reverse proxy if needed
  # nginx-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - pioneertown
  #   restart: unless-stopped
